"""drop legacy sales flags

Revision ID: 4ae992377ccc
Revises: ddb24f7f3e67
Create Date: 2026-07-13 15:14:29.070160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae992377ccc'
down_revision: Union[str, Sequence[str], None] = 'ddb24f7f3e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'is_songrim_partner')
    op.drop_column('hospitals', 'sales_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('sales_grade', sa.VARCHAR(), nullable=True))
    op.add_column('hospitals', sa.Column('is_songrim_partner', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
