"""add contracts, deliveries, inventory

Revision ID: 606416f06537
Revises: 4ae992377ccc
Create Date: 2026-07-13 16:06:15.227882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606416f06537'
down_revision: Union[str, Sequence[str], None] = '4ae992377ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('contract_date', sa.String(), nullable=True),
    sa.Column('buyer_hospital', sa.String(), nullable=True),
    sa.Column('buyer_biz_no', sa.String(), nullable=True),
    sa.Column('buyer_rep', sa.String(), nullable=True),
    sa.Column('buyer_address', sa.String(), nullable=True),
    sa.Column('buyer_phone', sa.String(), nullable=True),
    sa.Column('buyer_mobile', sa.String(), nullable=True),
    sa.Column('buyer_fax', sa.String(), nullable=True),
    sa.Column('sale_amount', sa.Integer(), nullable=False),
    sa.Column('sale_amount_note', sa.String(), nullable=True),
    sa.Column('etc_note', sa.String(), nullable=True),
    sa.Column('customer_request', sa.String(), nullable=True),
    sa.Column('install_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('진행중','보류','완료')", name='ck_contract_status'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=False),
    sa.Column('installation_date', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('site_type', sa.String(), nullable=False),
    sa.Column('maintenance', sa.String(), nullable=True),
    sa.Column('demo_result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("site_type IN ('delivery','demo')", name='ck_delivery_site_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inv_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_no', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('manufacture_date', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('purchase_price', sa.String(), nullable=True),
    sa.Column('purchase_from', sa.String(), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inv_supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_comments_contract', 'contract_comments', ['contract_id'], unique=False)
    op.create_table('contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qty', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_photos_contract', 'contract_photos', ['contract_id'], unique=False)
    op.create_table('delivery_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_comments_delivery', 'delivery_comments', ['delivery_id'], unique=False)
    op.create_table('delivery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('serial_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_photos_delivery', 'delivery_photos', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_delivery_photos_delivery', table_name='delivery_photos')
    op.drop_table('delivery_photos')
    op.drop_table('delivery_items')
    op.drop_index('idx_delivery_comments_delivery', table_name='delivery_comments')
    op.drop_table('delivery_comments')
    op.drop_index('idx_contract_photos_contract', table_name='contract_photos')
    op.drop_table('contract_photos')
    op.drop_table('contract_items')
    op.drop_index('idx_contract_comments_contract', table_name='contract_comments')
    op.drop_table('contract_comments')
    op.drop_table('inv_supplies')
    op.drop_table('inv_equipment')
    op.drop_table('deliveries')
    op.drop_table('contracts')
    # ### end Alembic commands ###
