"""initial schema

Revision ID: ddb24f7f3e67
Revises: 
Create Date: 2026-07-13 15:02:00.001993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb24f7f3e67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_master',
    sa.Column('grade_code', sa.String(), nullable=False),
    sa.Column('grade_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('gift_policy_note', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("grade_type IN ('discount','gift')", name='ck_grade_type'),
    sa.PrimaryKeyConstraint('grade_code')
    )
    op.create_table('page_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('page_key', sa.String(), nullable=False),
    sa.Column('can_access', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_folder_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_path', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('permission_level', sa.String(), nullable=False),
    sa.CheckConstraint("permission_level IN ('view','edit')", name='ck_storage_perm_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spec', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=False),
    sa.Column('hospital_type', sa.String(), nullable=False),
    sa.Column('hospital_dept', sa.String(), nullable=True),
    sa.Column('hospital_address', sa.String(), nullable=True),
    sa.Column('hospital_tel', sa.String(), nullable=True),
    sa.Column('business_reg_no', sa.String(), nullable=True),
    sa.Column('ceo_name', sa.String(), nullable=True),
    sa.Column('ceo_phone', sa.String(), nullable=True),
    sa.Column('discount_grade_code', sa.String(), nullable=True),
    sa.Column('gift_grade_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discount_grade_code'], ['grade_master.grade_code'], ),
    sa.ForeignKeyConstraint(['gift_grade_code'], ['grade_master.grade_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_norm', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sido', sa.String(), nullable=True),
    sa.Column('sigungu', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('ykiho', sa.String(), nullable=True),
    sa.Column('hospital_profile_id', sa.Integer(), nullable=True),
    sa.Column('is_songrim_partner', sa.Boolean(), nullable=False),
    sa.Column('sales_grade', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_profile_id'], ['hospital_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hosp_sido_norm', 'hospitals', ['sido', 'name_norm'], unique=False)
    op.create_index(op.f('ix_hospitals_hospital_profile_id'), 'hospitals', ['hospital_profile_id'], unique=False)
    op.create_index(op.f('ix_hospitals_name_norm'), 'hospitals', ['name_norm'], unique=False)
    op.create_index(op.f('ix_hospitals_sido'), 'hospitals', ['sido'], unique=False)
    op.create_table('supply_catalog_visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('hospital_profile_id', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['supply_catalog.id'], ),
    sa.ForeignKeyConstraint(['hospital_profile_id'], ['hospital_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', 'hospital_profile_id', name='uq_catalog_visibility')
    )
    op.create_table('supply_price_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('hospital_profile_id', sa.Integer(), nullable=False),
    sa.Column('override_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['supply_catalog.id'], ),
    sa.ForeignKeyConstraint(['hospital_profile_id'], ['hospital_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', 'hospital_profile_id', name='uq_price_override')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('hospital_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('songrim','hospital')", name='ck_user_role'),
    sa.ForeignKeyConstraint(['hospital_profile_id'], ['hospital_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('eq_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("category IN ('us','xray','ct','mri')", name='ck_equipment_category'),
    sa.CheckConstraint("source IN ('import','manual')", name='ck_equipment_source'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eq_cat_year', 'equipment', ['category', 'year'], unique=False)
    op.create_index('idx_eq_hosp_cat', 'equipment', ['hospital_id', 'category'], unique=False)
    op.create_table('sales_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_hosp', 'sales_notes', ['hospital_id'], unique=False)
    op.create_index('idx_notes_user', 'sales_notes', ['user_id'], unique=False)
    op.create_index('idx_notes_visit', 'sales_notes', ['visit_date'], unique=False)
    op.create_table('sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('staff_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_profiles')
    op.drop_table('sessions')
    op.drop_index('idx_notes_visit', table_name='sales_notes')
    op.drop_index('idx_notes_user', table_name='sales_notes')
    op.drop_index('idx_notes_hosp', table_name='sales_notes')
    op.drop_table('sales_notes')
    op.drop_index('idx_eq_hosp_cat', table_name='equipment')
    op.drop_index('idx_eq_cat_year', table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('users')
    op.drop_table('supply_price_overrides')
    op.drop_table('supply_catalog_visibility')
    op.drop_index(op.f('ix_hospitals_sido'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_name_norm'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_hospital_profile_id'), table_name='hospitals')
    op.drop_index('idx_hosp_sido_norm', table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_table('hospital_profiles')
    op.drop_table('supply_catalog')
    op.drop_table('storage_folder_permissions')
    op.drop_table('page_permissions')
    op.drop_table('grade_master')
    # ### end Alembic commands ###
